project0/home/urls.py
from django.urls import path
from . import views
app_name='home'
urlpatterns = [
    path('',views.index,name='thisindex'),
    path('about123/',views.about,name='aboutme'),
    path('contact/',views.contact,name='contactus'),
    path('service/',views.service,name='allservice'),#記得每行結尾用逗號,區隔!!
    path('upload/',views.upload,name='uploadfiles')#路由名/放在後端
]

project0/member/urls.py
from django.urls import path
from . import views
app_name='member'
urlpatterns = [
    path('', views.index,name='index'),
    path('create/', views.create,name='create'),
    path('update/<int:id>', views.update,name='update'),
    path('delete/<int:id>', views.delete,name='delete'),
    path('login/', views.login,name='login'),
    path('logout/', views.logout,name='logout'),
    path('captcha/', views.captcha,name='captcha'),
]

project0/project0/urls.py
from django.contrib import admin
from django.urls import path,include

#檔案上傳
from django.conf import settings
from django.conf.urls.static import static

from rest_framework.routers import DefaultRouter
from todo import views

router = DefaultRouter()
router.register(r'todo',views.TodoViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('product/',include('product.urls')),
    path('member/',include('member.urls')),
    path('jquery/',include('jquery.urls')),
    path('fridge/',include('fridge.urls')),
    path('api/',include(router.urls)),
    ]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

project0/member/models.py
from django.db import models

# Create your models here.
class Member(models.Model):
    username = models.CharField(max_length=20,null=False)
    password = models.CharField(max_length=10,null=False)
    useremail = models.EmailField(max_length=100,blank=True)
    userbirth = models.DateField(null=False)
    
    class Meta:
        db_table = "members"

project0/member/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
import datetime
from .models import Member
from django.contrib.staticfiles import finders

# Create your views here.
def index(request):  
    
    title = "會員管理"
    members = Member.objects.all()
    #todo 讀取會員資料傳給index.html
    
    return render(request,'member/index.html',locals())

def create(request):
    if request.method == 'POST':
        username = request.POST["username"]
        password = request.POST["password"]
        useremail = request.POST["useremail"]
        userbirth = request.POST["userbirth"]

        #todo 接收到的會員資料寫進資料庫
        Member.objects.create(username=username,password=password,useremail=useremail,userbirth=userbirth)
        #todo 新增完成後轉到http://localhost:8000/member
        return redirect("/member")
    title = "會員新增" 
    return render(request,'member/create.html',locals())

def update(request,id):
    if request.method == 'POST':        
        username = request.POST["username"]      
        useremail = request.POST["useremail"]
        userbirth = request.POST["userbirth"]

        #todo 修改資料庫中的會員資料
        member = Member.objects.get(id=int(id))
        member.username = username
        member.useremail = useremail
        member.userbirth = userbirth
        member.save()
        #todo 修改完成後轉到http://localhost:8000/member
        return redirect("/member")

    title = "會員修改"
    #todo 根據會員編號取得會員資料傳給update.html
    #再拿一次，這次拿剛剛修改過的資料。傳給update.html
    member = Member.objects.get(id=int(id))
    
    return render(request,'member/update.html',locals())

def delete(request,id):
    #todo 根據會員編號刪除會員資料
    member = Member.objects.get(id=int(id))
    member.delete()
    #todo 刪除完成後轉到http://localhost:8000/member
    return redirect('/member')

def login(request):
    if request.method == "POST":
        email = request.POST['useremail']
        pwd = request.POST['userpassword']
        captcha = request.POST['captcha']
        if request.session['captcha'] == captcha:
            member = Member.objects.filter(useremail=email,password=pwd).values('username')

            if member:
                themember = member[0]
                response = HttpResponse("<script>alert('yes!');location.href='/member/'</script>")
                if 'rememberme' in request.POST.keys() and request.POST['rememberme']:
                    expiresdate = datetime.datetime.now() and datetime.timedelta(days=7)
                    response.set_cookie("name",themember['username'],expires=expiresdate)
                else:
                    response.set_cookie("name",themember['username'])
                    return response
            else:
                return HttpResponse("<script>alert('登入失敗，密碼錯誤！');location.href='/member/login'</script>")
        else:
            return HttpResponse("<script>alert('驗證碼輸入錯誤，請重新輸入');location.href='/member/login'</script>")
    title = "會員登入"
    return render(request,'member/login.html',locals())

def logout(request):
    response = HttpResponse("<script>alert('已登出');location.href='/member/login'</script>")
    response.delete_cookie('name')
   
    return response
def checkname(request,name):
    # name = request.GET['name'];
    # 檢查name是否在資料庫中
    # SQL語法  select username where username='Jack'
    # ORM Member.objects.filter(username=name)
    result = Member.objects.filter(username=name)
    if result :
        message = "帳號已存在"
    else:
        message = "帳號不存在"
        
    return HttpResponse(message)

def captcha(request):    
    import random
    # 安裝 pillow  pip install pillow
    from PIL import Image,ImageDraw,ImageFont
    list1 = random.sample(['0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F'],5)
    txt = ''.join(list1)    
    
    # todo 將產生的數字及字母存到session中
    request.session['captcha'] = txt  
    
    width = 15 * 4
    height = 35
    image = Image.new('RGB', (width, height), (255, 255, 255))    
    # 下載字體https://fonts.google.com/
    thefont = finders.find('fonts/Kavivanar-Regular.ttf')
    font = ImageFont.truetype(thefont, 16)   
    draw = ImageDraw.Draw(image)
    draw.text((5, 5), txt,font=font, fill=(255, 0, 0))
    response = HttpResponse(content_type="image/png")
    image.save(response, "PNG")
    return response

project0/member/templates/member/create.html
{% extends 'base.html'%}
{% block 'main' %}
<form method="POST">
    {% csrf_token %}   
    <div class="form-group row">
        <label for="username" class="col-sm-2 col-form-label">姓名</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" name="username" id="username" placeholder="User Name">
        </div>
    </div>
    <div class="form-group row">
        <label for="password" class="col-sm-2 col-form-label">密碼</label>
        <div class="col-sm-10">
            <input type="password" class="form-control" name="password" id="password" placeholder="Password">
        </div>
    </div>
    <div class="form-group row">
        <label for="useremail" class="col-sm-2 col-form-label">電子郵件</label>
        <div class="col-sm-10">
            <input type="email" class="form-control" name="useremail" id="useremail" placeholder="User Email">
        </div>
    </div>
    <div class="form-group row">
        <label for="userbirth" class="col-sm-2 col-form-label">生日</label>
        <div class="col-sm-10">
            <input type="date" class="form-control" name="userbirth" id="userbirth" placeholder="Birthday">
        </div>
    </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-10 offset-md-2">
            <button type="submit" class="btn btn-primary"><i class="fa fa-bath" aria-hidden="true"></i> 新增</button>
        </div>
    </div>
</form>
{% endblock %}
{% block script %}
<script>
//DOM Tree 產生
    $(document).ready(function(){
        $('#username').blur(function(){
            var name = $(this).val();
            // todo 檢查帳號是否存在
            //將帳號傳到伺服器上，由伺服器程式連到資料庫檢查帳號是否存在資料庫裏面
            //回應存在or不存在
            $.post('/member/checkname/' + name,function(data){
            $('#username~div').text(data)
            })
        })
    })
</script>
{% endblock %}

project0/member/templates/member/index.html
{% extends 'base.html'%}
{% block 'main' %}
<a href="{% url "member:create" %}" class="btn btn-primary mb-3"><i class="fa fa-plus-circle" aria-hidden="true"></i> 會員新增</a>
<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>姓名</th>
            <th>電子郵件</th>
            <th>生日</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for member in members %}
        <tr>
            <td>{{member.id}}</td>
            <td>{{member.username}}</td>
            <td>{{member.useremail}}</td>
            <td>{{member.userbirth}}</td>
            <td>
                <a href="{% url "member:update" member.id %}" class="btn btn-info mr-2">修改</a>
                <a href="{% url "member:delete" member.id %}" class="btn btn-danger">刪除</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

project0/member/templates/member/login.html
{% extends "base.html" %} {% block 'main' %}
<form method="POST">
  {% csrf_token %}
  <div class="form-group">
    <label for="useremail">Email address</label>
    <input type="email" class="form-control" id="useremail" name="useremail" aria-describedby="emailHelp" placeholder="Enter email">
  </div>
  <div class="form-group">
    <label for="userpassword">Password</label>
    <input type="password" class="form-control" name="userpassword" id="userpassword" placeholder="Password">
  </div>
  <div class="form-group">
      <input type="text" name="captcha" id="captcha" placeholder="驗證碼">
      <img id="img_captcha" src="/member/captcha">
      <button id="btn_captcha" type="button">
        <i class="fa fa-refresh" aria-hidden="true"></i>
      </button>
    </div>                          
  <div class="form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1" name="rememberme" value="yes">
    <label class="form-check-label" for="exampleCheck1"></label>記住我
  </div>
  <button type="submit" class="btn btn-primary mt-2">
    <i class="fa fa-sign-in" aria-hidden="true"></i>登入</button>
</form>
{% endblock %}
{% block script %}
<script>
  $('#btn_captcha').click(function () {
    var xhr = new XMLHttpRequest();
    xhr.open("GET", "/member/captcha");
    xhr.responseType = "arraybuffer";
    xhr.addEventListener("load",function(event) {
      var blob = new Blob([xhr.response], {type: "image/png"});
      var imageUrl = window.URL.createObjectURL(blob);   
      $('#img_captcha').attr('src',imageUrl)
    });
    xhr.send();    
  })
</script> 
{% endblock %}

project0/member/templates/member/update.html
{% extends 'base.html'%}
{% block 'main' %}
<form method="POST">
    {% csrf_token %}   
    <div class="form-group row">
        <label for="username" class="col-sm-2 col-form-label">姓名</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" name="username" id="username" placeholder="User Name" value="{{member.username}}">
        </div>
    </div>
    <div class="form-group row">
        <label for="useremail" class="col-sm-2 col-form-label">電子郵件</label>
        <div class="col-sm-10">
            <input type="email" class="form-control" name="useremail" id="useremail" placeholder="User Email" value="{{member.useremail}}">
        </div>
    </div>
    <div class="form-group row">
        <label for="userbirth" class="col-sm-2 col-form-label">生日</label>
        <div class="col-sm-10">
            <input type="date" class="form-control" name="userbirth" id="userbirth" placeholder="Birthday" value="{{member.userbirth | date:'Y-m-d'}}">
        </div>
    </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-10 offset-md-2">
            <button type="submit" class="btn btn-primary"><i class="fa fa-bath" aria-hidden="true"></i> 修改</button>
        </div>
    </div>
</form>
{% endblock %}