project0/home/urls.py
from django.urls import path
from . import views
app_name='home'
urlpatterns = [
    path('',views.index,name='thisindex'),
    path('about123/',views.about,name='aboutme'),
    path('contact/',views.contact,name='contactus'),
    path('service/',views.service,name='allservice'),#記得每行結尾用逗號,區隔!!
    path('upload/',views.upload,name='uploadfiles')#路由名/放在後端
]

project0/member/urls.py
from django.urls import path
from . import views
app_name='member'
urlpatterns = [
    path('', views.index,name='index'),
    path('create/', views.create,name='create'),
    path('update/<int:id>', views.update,name='update'),
    path('delete/<int:id>', views.delete,name='delete'),
    path('login/', views.login,name='login'),
    path('logout/', views.logout,name='logout'),
    path('captcha/', views.captcha,name='captcha'),
]

project0/product/urls.py
from django.urls import path
from . import views
app_name="product"
urlpatterns = [ 
    #http://localhost:8000/product
    path('',views.index,name='index'),
    #http://localhost:8000/product/create
    path('create/',views.create,name='create'),
    #http://localhost:8000/product/update
    path('update/<int:id>',views.update,name='update'),
    #http://localhost:8000/product/update
    path('delete/<int:id>',views.update,name='delete')]

project0/project0/urls.py
from django.contrib import admin
from django.urls import path,include

#檔案上傳
from django.conf import settings
from django.conf.urls.static import static

from rest_framework.routers import DefaultRouter
from todo import views

router = DefaultRouter()
router.register(r'todo',views.TodoViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('product/',include('product.urls')),
    path('member/',include('member.urls')),
    path('jquery/',include('jquery.urls')),
    path('fridge/',include('fridge.urls')),
    path('api/',include(router.urls)),
    ]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

project0/templates/base.html
<!doctype html>
<html lang="zh-tw">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy"
        crossorigin="anonymous">
        <script src="https://use.fontawesome.com/f57c5cc844.js"></script>

    <title>產品管理</title>
</head>

<body>
{% include 'nav.html' %}
    <div class="container">
        <div class="row">
            {% if title != "todo app" %}
            <div class="col-3">
                <div class="alert alert-primary" role="alert">
                    某些內容
                </div>
            </div>
            {% endif %}
            <div class="col">
                <div class="card">
                    <div class="card-header">
                        {{ title }}
                    </div>
                    <div class="card-body">
                        {% block 'main' %} {% endblock %}
                    </div>
                </div>
            </div>
        </div>


    </div>
    {% include 'footer.html' %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!-- slim版本不支援ajax功能 -->
    <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment.min.js"></script>
    {% block script %}{% endblock %}
</body>

</html>

project0/templates/footer.html
<footer>
    <div class="container text-center bg-info pt-2 pb-2">
        <p>&copy; Copyright 2018 - AIEN </p>
    </div>
</footer>

project0/templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-secondary mb-3">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li>
                <img src="{% static 'images/logo.png' %}" alt="">
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'home:thisindex' %}">首頁
                    <!-- <span class="sr-only">(current)</span> -->
                </a>
            </li>

            <!-- <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:aboutme' %}">關於AIEN</a>
                </li> -->
            <!-- <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:contactus' %}">聯絡我們</a>
                </li> -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home:allservice' %}">服務項目</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'product:index'%}">商品與服務</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'member:index'%}">會員管理</a>
            </li>

        </ul>
        <!-- template引擎註解方法 -->
        {# if name == None #}
        <!-- template引擎註解方法 -->
        {% if request.COOKIES.name %}
        <span>{{ request.COOKIES.name }} 哩厚</span>
        {% else %}
        <span>請先</span>
        {% endif %}
        <ul class="navbar-nav float-right">

            <li class="nav-item">
                <!-- template引擎註解方法 -->
                {# if name == None #}
                <!-- template引擎註解方法 -->
                {% if request.COOKIES.name %}
                <a class="nav-link" href="{% url "member:logout" %}">登出</a>
                {% else %}
                <a class="nav-link" href="{% url "member:login" %}">登入</a>
                {% endif %}
            </li>
        </ul>

    </div>
</nav>