project0/home/urls.py
from django.urls import path
from . import views
app_name='home'
urlpatterns = [
    path('',views.index,name='thisindex'),
    path('about123/',views.about,name='aboutme'),
    path('contact/',views.contact,name='contactus'),
    path('service/',views.service,name='allservice'),#記得每行結尾用逗號,區隔!!
    path('upload/',views.upload,name='uploadfiles')#路由名/放在後端
]

project0/product/urls.py
from django.urls import path
from . import views
app_name="product"
urlpatterns = [ 
    #http://localhost:8000/product
    path('',views.index,name='index'),
    #http://localhost:8000/product/create
    path('create/',views.create,name='create'),
    #http://localhost:8000/product/update
    path('update/<int:id>',views.update,name='update'),
    #http://localhost:8000/product/update
    path('delete/<int:id>',views.update,name='delete')]

project0/project0/urls.py
from django.contrib import admin
from django.urls import path,include

#檔案上傳
from django.conf import settings
from django.conf.urls.static import static

from rest_framework.routers import DefaultRouter
from todo import views

router = DefaultRouter()
router.register(r'todo',views.TodoViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('product/',include('product.urls')),
    path('member/',include('member.urls')),
    path('jquery/',include('jquery.urls')),
    path('fridge/',include('fridge.urls')),
    path('api/',include(router.urls)),
    ]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

project0/product/views.py
from django.shortcuts import render,redirect
from . import modelscategory
from . import modelsproduct
from django.core.files.storage import FileSystemStorage

# Create your views here.
def index(request):
    title = '商品管理'
    product = modelsproduct.Product()
    products = product.all()
    return render(request,'product/index.html',locals())

def create(request):

    if request.method =='POST' and request.FILES['productimage']: #FILES須為大寫，後方的值須放在[]內
        myfile = request.FILES['productimage']
        categoryid = request.POST['categoryid']
        modelnumber = request.POST['modelnumber']
        modelname = request.POST['modelname']
        unitcost = request.POST['unitcost']
        description = request.POST['description']
        myfile = request.FILES['productimage']
        productimage = myfile.name

        #新增資料
        product = modelsproduct.Product()
        datas = tuple([categoryid,modelnumber,modelname,unitcost,productimage,description])
        product.create(datas)

        #檔案上傳
        files1 = FileSystemStorage()
        files1.save(myfile.name,myfile) #productimage.name得到的檔名指定給myfile

        return redirect("/product")#redirect需要import
    category = modelscategory.Category()
    datas = category.all()      
    title = '商品新增'
    return render(request,'product/create.html',locals())

def update(request, id):
    title = '商品修改'
    category = modelscategory.Category()
    categories = category.all()

    product = modelsproduct.Product()
    singleproduct = product.single(id)

    return render(request,'product/update.html',locals())

def delete(request, id):
    product = modelsproduct.Product()
    product.delete(id)
    return redirect("/product")

project0/product/templates/product/create.html
{% extends 'base.html' %}
{% block 'main' %}
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="form-group row">
    <label for="categoryid" class="col-sm-2 col-form-label">CategoryID</label>
    <div class="col-sm-10">
        <select id="categoryid" name="categoryid" class="form-control" >
           <option value="0">請選擇</option>            
            {% for category in datas %}
              <option value="{{category.0}}">{{category.1}}</option>
            {% endfor %}
        </select>       
    </div>
  </div>
  <div class="form-group row">
    <label for="modelnumber" class="col-sm-2 col-form-label">ModelNumber</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="modelnumber" name="modelnumber" placeholder="ModelNumber">
    </div>
  </div>
  <div class="form-group row">
    <label for="modelname" class="col-sm-2 col-form-label">ModelName</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="modelname" name="modelname" placeholder="ModelName">
    </div>
  </div>
  <div class="form-group row">
    <label for="unitcost" class="col-sm-2 col-form-label">UnitCost</label>
    <div class="col-sm-10">
      <input type="number" class="form-control" id="unitcost" name="unitcost" placeholder="UnitCost">
    </div>
  </div>
  <div class="form-group row">
    <label for="productimage" class="col-sm-2 col-form-label">ProductImage</label>
    <div class="col-sm-10">
      <input type="file" class="form-control" id="productimage" name="productimage" placeholder="ProuctImage">
      <img src="" id="img1"><!-- 要放入準備上傳檔案的預覽圖 -->
    </div>
  </div>
  <div class="form-group row">
    <label for="description" class="col-sm-2 col-form-label">Description</label>
    <div class="col-sm-10">
        <textarea id="description" name="description" class="form-control" placeholder="Description"></textarea>
    
    </div>
  </div>
  
  
  <div class="form-group row">
    <div class="col-sm-10">
      <button type="submit" class="btn btn-primary">新增</button>
    </div>
  </div>
</form>
{% endblock %}
{% block script %}
<script>
  document.querySelector("#productimage").addEventListener("change",function(event){
    var theFile = this.files[0];
    var reader = new FileReader();
    var theImg = document.querySelector("#img1");
    reader.readAsDataURL(theFile);//使用reader獲得thefile的路徑並觸發load動作。
    reader.addEventListener("load",function(event){
      theImg.src = event.target.result;
    })
  })
</script>
{% endblock %}

project0/product/templates/product/index.html
{% extends 'base.html' %}
{% block 'main' %}
<a href="{% url 'product:create' %}" class="btn btn-primary mb-3"><i class="fa fa-plus-circle" aria-hidden="true"></i> 新增商品</a>
<table class="table table-bordered">
    <thead>
        <tr class="row">
            <th>#id</th>
            <th>型號</th>
            <th>名稱</th>
            <th>價格</th>
            <th>圖片</th>
            <th>編輯</th>
        </tr>
    </thead>
    <tbody>
        {% for product in products %}
        <tr class="row">
            <td class="col-1">{{product.0}}</td>
            <td class="col-2">{{product.2}}</td>
            <td class="col-3">{{product.3}}</td>
            <td class="col-2">{{product.5}}</td>
            <td class="col-2"><img src="/media/{{product.4}}" class="img-thumbnail"></td>
            <td class="col-2">
                <a href="{% url 'product:update' product.0 %}" class="btn btn-secondary mr-3"></a>
                <a href="{% url 'product:delete' product.0 %}"class="btn btn-danger"></a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

project0/product/templates/product/update.html
{% extends 'base.html' %}
{% block 'main' %}
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="form-group row">
    <label for="categoryid" class="col-sm-2 col-form-label">CategoryID</label>
    <div class="col-sm-10">
        <select id="categoryid" name="categoryid" class="form-control" >
           <option value="0">請選擇</option>            
            {% for category in datas %}
              <option value="{{category.0}}">{{category.1}}</option>
            {% endfor %}
        </select>       
    </div>
  </div>
  <div class="form-group row">
    <label for="modelnumber" class="col-sm-2 col-form-label">ModelNumber</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="modelnumber" name="modelnumber" placeholder="ModelNumber">
    </div>
  </div>
  <div class="form-group row">
    <label for="modelname" class="col-sm-2 col-form-label">ModelName</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="modelname" name="modelname" placeholder="ModelName">
    </div>
  </div>
  <div class="form-group row">
    <label for="unitcost" class="col-sm-2 col-form-label">UnitCost</label>
    <div class="col-sm-10">
      <input type="number" class="form-control" id="unitcost" name="unitcost" placeholder="UnitCost">
    </div>
  </div>
  <div class="form-group row">
    <label for="productimage" class="col-sm-2 col-form-label">ProductImage</label>
    <div class="col-sm-10">
      <input type="file" class="form-control" id="productimage" name="productimage" placeholder="ProuctImage">
    </div>
  </div>
  <div class="form-group row">
    <label for="description" class="col-sm-2 col-form-label">Description</label>
    <div class="col-sm-10">
        <textarea id="description" name="description" class="form-control" placeholder="Description"></textarea>
    
    </div>
  </div>
  
  
  <div class="form-group row">
    <div class="col-sm-10">
      <button type="submit" class="btn btn-primary">新增</button>
    </div>
  </div>
</form>
{% endblock %}