icethem/fridge/urls.py
from django.urls import path
from . import views
app_name='fridge'
urlpatterns = [
    path('',views.index,name='index'),#記得每行結尾用逗號,區隔!!#路由名/放在後端
    path('create',views.create,name='create'),
    path('update',views.update,name='update'),
    path('update/<int:id>',views.update,name='update'),
    path('delete/<int:id>',views.delete ,name='delete'),
    path('stacks',views.stacks,name='stacks'),
    path('sort/<str:foodid>',views.sort ,name='sort'),

]

icethem/icethem/urls.py
from django.contrib import admin
from django.urls import path,include

#檔案上傳
from django.conf import settings
from django.conf.urls.static import static

from rest_framework.routers import DefaultRouter
# from todo import views

# router = DefaultRouter()
# router.register(r'todo',views.TodoViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('',include('home.urls')),
    path('fridge/',include('fridge.urls')),
    # path('api/',include(router.urls)),
    path('user/',include('user.urls')),
    ]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

icethem/user/urls.py
from django.urls import path
from . import views
app_name='user'
urlpatterns = [
    path('', views.index,name='index'),
    path('create/', views.create,name='create'),
    path('update/<int:id>', views.update,name='update'),
    path('delete/<int:id>', views.delete,name='delete'),
    path('login/', views.login,name='login'),
    path('logout/', views.logout,name='logout'),
    path('checkname/<str:name>',views.checkname,name='checkname'),
    path('captcha/',views.captcha,name='captcha')
]

icethem/fridge/models.py
from django.db import models

# Create your models here.

icethem/user/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    username = models.CharField(max_length=20,null=False)
    password = models.CharField(max_length=10,null=False)
    useremail = models.EmailField(max_length=100,blank=True)
    # userbirth = models.DateField(null=False)
    
    class Meta:
        db_table = "Users"

icethem/fridge/views.py
from django.shortcuts import render,redirect
from . import modelsfoods
from django.http import HttpResponse
from django.core.files.storage import FileSystemStorage

def index(request):
    title = '食物管理'
    food = modelsfoods.Foods()
    foodsall = food.all()
    print(foodsall)
    return render(request,'fridge/index.html',locals())

def create(request):
    if request.method == "POST" and request.FILES['foodimg']:
        foodname = request.POST['foodname']
        foodtype = request.POST['foodtype']
        iceddate = request.POST['iceddate']
        expiredate = request.POST['expiredate']
        description = request.POST['description']
        thefile = request.FILES['foodimg']
        foodimg = thefile.name

        #資料新增
        food = modelsfoods.Foods()
        datas = tuple([foodname,foodtype,iceddate,expiredate,foodimg,description])
        food.create(datas)

        #檔案上傳
        fs = FileSystemStorage()
        fs.save(thefile.name,thefile)
        
        return redirect("/fridge")

    foods = modelsfoods.Foods()
    datas = foods.all()

    title = "商品新增"
    return render(request,'fridge/create.html',locals())

def update(request, id):
    if request.method == "POST" and request.FILES['foodimg']:
        foodname = request.POST['foodname']
        foodtype = request.POST['foodtype']
        iceddate = request.POST['iceddate']
        expiredate = request.POST['expiredate']
        description = request.POST['description']
        thefile = request.FILES['foodimg']
        foodimg = thefile.name

        food = modelsfoods.Foods()
        datas = tuple([foodname,foodtype,iceddate,expiredate,foodimg,description])
        food.update(datas)

        #檔案上傳
        fs = FileSystemStorage()
        fs.save(thefile.name,thefile)
        
        return redirect('fridge/update.html',locals())

def delete(reqeust, id):
    food = modelsfoods.Foods()
    food.delete(id)
    return redirect("/fridge")

def fridge(request):
    title = 'fridge'

    return render(request,'fridge/fridge.html',locals())
def stacks(request):
    title = 'stacks'
    food = modelsfoods.Foods()
    foodsall = food.all()
    return render(request,'fridge/stacks.html',locals())
def sort(request,foodid):
    if request.method == "GET" :
        foodid = request.POST['foodid']
    return HttpResponse("food:"+foodid)

icethem/user/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
import datetime
from .models import User
from django.contrib.staticfiles import finders
# Create your views here.
def index(request):  
    
    title = "會員管理"

    #todo 讀取會員資料傳給index.html
    users = User.objects.all()
    # print(users)
    # name = request.COOKIES['name']
    return render(request,'user/index.html',locals())

def create(request):
    if request.method == 'POST':
        username = request.POST["username"]
        password = request.POST["password"]
        useremail = request.POST["useremail"]
        # userbirth = request.POST["userbirth"]

        #todo 接收到的會員資料寫進資料庫
        User.objects.create(username=username,useremail=useremail,password=password)
        
        #todo 新增完成後轉到http://localhost:8000/user
        return redirect("/user")
       
    title = "會員新增" 
    return render(request,'user/create.html',locals())

def update(request,id):
    if request.method == 'POST':        
        username = request.POST["username"]      
        useremail = request.POST["useremail"]


        #todo 修改資料庫中的會員資料
        user = User.objects.get(id=int(id))
        User.username = username
        User.useremail = useremail
        User.save()
        #todo 修改完成後轉到http://localhost:8000/user
        return redirect("/user")

    title = "會員修改"
    #todo 根據會員編號取得會員資料傳給update.html
    user = User.objects.get(id=int(id))

    return render(request,'user/update.html',locals())

def delete(request,id):
    #todo 根據會員編號刪除會員資料
    user = User.objects.get(id=int(id))
    user.delete()

    #todo 刪除完成後轉到http://localhost:8000/user
    return redirect('/user')

def login(request):   
    if request.method == "POST":
        email = request.POST['useremail']
        pwd = request.POST['userpassword']
        captcha = request.POST['captcha']
        if request.session['captcha'] == captcha:
            user = User.objects.filter(useremail=email,password=pwd).values('username')
        
            if user:
                theuser = user[0]            
                response = HttpResponse("<script>alert('登入成功');location.href='/user/'</script>")
                if 'reuserme' in request.POST.keys() and request.POST['reuserme']:
                    expiresdate = datetime.datetime.now() + datetime.timedelta(days=7)
                    response.set_cookie("name",theuser['username'],expires=expiresdate)
                else:
                    response.set_cookie("name",theuser['username'])
                return response
            else:
                return HttpResponse("<script>alert('登入失敗，密碼錯誤');location.href='/user/login'</script>")
        else:
            return HttpResponse("<script>alert('驗證碼輸入錯誤，請重新輸入');location.href='/user/login'</script>")
    title = "會員登入"
    return render(request,'user/login.html',locals())

def logout(request):
    response = HttpResponse("<script>alert('登出');location.href='/user/login'</script>")
    response.delete_cookie('name')
    return response

def checkname(request,name):
    # name = request.GET['name'];
    # 檢查name是否在資料庫中
    # SQL語法  select username where username='Jack'
    # ORM User.objects.filter(username=name)
    result = User.objects.filter(username=name)
    if result :
        message = "帳號已存在"
    else:
        message = "帳號不存在"
        
    return HttpResponse(message)

def captcha(request):    
    import random
    # 安裝 pillow  pip install pillow
    from PIL import Image,ImageDraw,ImageFont
    list1 = random.sample(['0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F'],5)
    txt = ''.join(list1)    
    
    # todo 將產生的數字及字母存到session中
    request.session['captcha'] = txt  
    
    width = 15 * 5
    height = 30
    image = Image.new('RGB', (width, height), (255, 255, 255))    
    # 下載字體https://fonts.google.com/
    thefont = finders.find('fonts/GiveYouGlory.ttf')
    font = ImageFont.truetype(thefont, 22)   
    draw = ImageDraw.Draw(image)
    draw.text((5, 5), txt,font=font, fill=(255, 0, 0))
    response = HttpResponse(content_type="image/png")
    image.save(response, "PNG")
    return response

icethem/fridge/templates/fridge/create.html
{% extends 'base.html' %}
{% block 'main' %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group row">
      <label for="foodname" class="col-sm-2 col-form-label">foodname</label>
      <div class="col-sm-10">
          <input type="text" id="foodname" name="foodname" class="form-control" >          
      </input>       
      </div>
    </div>
    <div class="form-group row">
      <label for="foodtype" class="col-sm-2 col-form-label">foodtype</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="foodtype" name="foodtype" placeholder="foodtype">
      </div>
    </div>
    <div class="form-group row">
      <label for="iceddate" class="col-sm-2 col-form-label">iceddate</label>
      <div class="col-sm-10">
        <input type="date" class="form-control" id="iceddate" name="iceddate" placeholder="iceddate">
      </div>
    </div>
    <div class="form-group row">
      <label for="expiredate" class="col-sm-2 col-form-label">expiredate</label>
      <div class="col-sm-10">
        <input type="date" class="form-control" id="expiredate" name="expiredate" placeholder="expiredate">
      </div>
    </div>
    <div class="form-group row">
      <label for="foodimg" class="col-sm-2 col-form-label">FoodImg</label>
      <div class="col-sm-10">
        <input type="file" class="form-control" id="foodimg" name="foodimg" placeholder="foodimg">
        <img src="" id="img1">
      </div>
    </div>
    <div class="form-group row">
      <label for="description" class="col-sm-2 col-form-label">Description</label>
      <div class="col-sm-10">
          <textarea id="description" name="description" class="form-control" placeholder="Description"></textarea>
      
      </div>
    </div>
    
    
    <div class="form-group row">
      <div class="col-sm-10">
        <button type="submit" class="btn btn-primary"><i class="fa fa-plus" aria-hidden="true"></i> 新增</button>
      </div>
    </div>
  </form>


{% endblock %}

{% block script %}
  <script>
    document.querySelector("#foodimg").addEventListener("change",function(event){
       //FileReader
       var theFile = this.files[0];
       var reader = new FileReader();
       var theImg = document.querySelector("#img1");
       reader.readAsDataURL(theFile);
       reader.addEventListener("load",function(event){
          theImg.src = event.target.result;
       })
    })
  </script>
{% endblock %}

icethem/fridge/templates/fridge/fridge.html
{% extends 'base.html' %}

{% block style %}
<style>
    * {
    margin: 0;
    padding: 0;
}
#wholepage{
    width: 100%;
    margin: auto;
    border:1px solid gray;
}
nav{

}
.menu {
    overflow: auto;
    width: 100%;
    list-style-type: none;
    background-color: rgb(91, 235, 203);
    border-top-right-radius: 15px;
    border-top-left-radius: 15px;
    border-bottom: 3px solid #cccccc;
}

.menu li {
    float: left;
    width: 7em;
    /*為了讓連結區域能依字型大小的變化自動放大,因此在指定width屬性時採用em為單位*/
}

.menu li a {
    display: block;
    width: 100%;
    line-height: 2.5em;
    text-decoration: none;
    text-align: center;
    color: rgb(82, 207, 223, 0.733);
}

.menu li a:hover {
    color: aliceblue;
    background-color: rgb(39, 153, 128);
}
.midbody{
    margin: auto;
    width:30%;
    height:1000px;
    float: left;
}
.fri{
    /* margin: auto; */
    /* float: left; */
    width:100%;
    height:100%;
    background-color: rgb(253, 230, 126);
    border:1px solid rgb(59, 63, 63);
    border-radius: 10px;
    list-style-type: none;
    
}
.sta{
    /* margin:auto; */
    float:left;
    border-radius: 8px;
    background-color: azure;
    box-shadow: 5px;
    width: 400px;
    height:120px;
    border-bottom: 3px solid  rgb(59, 63, 63);
    /* margin:4px; */
}
h1{
    margin:auto;
    text-align: center;
}
.door{
width:20%;
height:1000px;
float: left;
}
#stacks{
list-style-type: none;
width:20%;
height:1000px;
float: left;
}

</style>
{% endblock %}



{% block 'main' %}
<body>
    <div style="width:10%;height:100%;float:left">

    </div>

    <div id="wholepage">

        
        <ul id="stacks" name="sta11">
            <li id="staid" class="sta" name="sta1">
                <div>foods</div>
            </li>
        </ul>
<!-- ................................................ -->

        <div class="door" id="door1" name="dragtarget">

        </div>

<!-- ................................................ -->

        <div class="midbody" name="dragtarget">
            <ul class ="fri" id="sortable">

            </ul>
        </div>

<!-- ................................................ -->

        <div class="door" id="door2" name="dragtarget">

        </div>

</div>

</body>
{% endblock %}



{% block script %}
<script>
    $(function() {
      $( "#sortable" ).sortable({
        revert: true
      });
      $( "#staid" ).draggable({
        connectToSortable: "#sortable",
        helper: "clone",
        revert: "invalid"
      });
      $( "ul, li" ).disableSelection();
    });
  
          // $(function() {
          // //   $( ".sta" ).draggable({ snap: true,distance: 40  });
          // // //   $( ".sta" ).draggable({ snap: "div[name$='dragtarget']" });
          // $( ".sta" ).draggable({ snap: "div[name$='dragtarget']", snapMode: "inner",helper: "clone", opacity: "0.5",revert: "invalid", });
          // // //   $( "#draggable4" ).draggable({ grid: [ 20, 20 ] });
          // // //   $( "#draggable5" ).draggable({ grid: [ 80, 80 ] });
          // $(".door").droppable( { accept: ".sta", hoverClass: "dropHover", } ); 
          // });
  </script>
{% endblock %}

icethem/fridge/templates/fridge/index.html
{% extends 'base.html' %}
{% block 'main' %}
<a href="{% url 'fridge:create' %}" class="btn btn-primary mb-3"><i class="fa fa-plus-circle" aria-hidden="true"></i> 新增食物</a>
<div>
    <p>testgit</p>
<table class="table">
    <thead>
        <tr class="row">
                <th class="col-1"></th>
            <th class="col-1">食物名稱</th>
            <th class="col-1">食物類型</th>
            <th class="col-1">保存日期</th>
            <th class="col-1">保存期限</th>
            <th class="col-1">食物圖片</th>
            <th class="col-1"></th>
            <th class="col-1">備註</th>
            <th class="col-1">編輯</th>
        </tr>
    </thead>
    <tbody>
        {% for food in foodsall %}
        <tr class="row">
                <th class="col-1"></th>
            <td class="col-1">{{food.2}}</td>
            <td class="col-1">{{food.3}}</td>
            <td class="col-1">{{food.4}}</td>
            <td class="col-1">{{food.5}}</td>
            <td class="col-2"><img src="/media/{{food.6}}" class="img-thumbnail img-fluid"></td>
            <td class="col-1">{{food.7}}</td>
            <td class="col-1">
                    <a href="{% url 'fridge:update' food.0 %}" class="btn btn-secondary"><i class="fa fa-pencil" aria-hidden="true"></i> </a>
                    <a href="{% url 'fridge:delete' food.0 %}" class="btn btn-danger"><i class="fa fa-trash" aria-hidden="true"></i> </a>
                </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
{% endblock %}

icethem/fridge/templates/fridge/stacks.html
{% extends 'base.html' %}
{% block style %}
<style>
    * {
    margin: 0;
    padding: 0;
}
#wholepage{
    width: 100%;
    margin: auto;
    border:1px solid gray;
}
nav{

}
.menu {
    overflow: auto;
    width: 100%;
    list-style-type: none;
    background-color: rgb(91, 235, 203);
    border-top-right-radius: 15px;
    border-top-left-radius: 15px;
    border-bottom: 3px solid #cccccc;
}

.menu li {
    float: left;
    width: 7em;
    /*為了讓連結區域能依字型大小的變化自動放大,因此在指定width屬性時採用em為單位*/
}

.menu li a {
    display: block;
    width: 100%;
    line-height: 2.5em;
    text-decoration: none;
    text-align: center;
    color: rgb(82, 207, 223, 0.733);
}

.menu li a:hover {
    color: aliceblue;
    background-color: rgb(39, 153, 128);
}
.midbody{
    margin: auto;
    width:100%;
    height:1000px;
    float: left;
}
.fri{
    margin-top:auto;
    /* float: left; */

    width:100%;
    height:30%;
    background-color: rgb(253, 230, 126);
    border:1px solid rgb(59, 63, 63);
    border-radius: 1000px;
    list-style-type: none;
    
}
.sta{
    margin:5px;
    float:left;
    border-radius: 8px;
    background-color: azure;
    border-bottom: 3px solid  rgb(59, 63, 63);
    width:auto;
    height:auto;
    max-height:100;
    display: inline;
    float: left;
    /* margin:4px; */
}
h1{
    margin:auto;
    text-align: center;
}
.door{
width:20%;
height:250px;
float: left;
}
#stacks{
list-style-type: none;
width:20%;
height:250px;
float: left;
}

.thumbnail{
    width:auto;
    height:auto;
    max-width:100%;
    max-height:75px;
}

.place{
    width:auto;
    height:500px;
    max-width:100%;
    max-height:100%;

}
.sortableone{
    margin-top:auto;
    /* float: left; */

    width:100%;
    height:30%;
    background-color: rgb(253, 230, 126);
    border:1px solid rgb(59, 63, 63);
    border-radius: 1000px;
    list-style-type: none;
}

#devnull * {
  display: none;
}
#devnull {
  margin-left: 500px;
  width: 200px;
  height: 200px;
  background: rgb(0, 132, 255);
}


</style>
{% endblock %}
<body>
{% block 'main' %}





<!-- 
    <div style="width:10%;height:100%;float:left">

    </div> -->

    <div id="wholepage">

    <div class = "place">
        <ul id="stacks" name="sta11">
            <!-- 迴圈產生多個物件時function不要綁定ID!!他只會取一個 -->
        {% for food in foodsall %}    
            <li id="staid" class="sta" name="drag">
            <img src="/media/{{food.6}}" class="thumbnail">
            </li>
        {% endfor %}
        </ul>
    </ul>
    <div id='devnull'>
    </div>
    </div>
    <hr>
<!-- ................................................ -->
<!-- 
        <div class="door" id="door1" name="dragtarget">

        </div> -->

<!-- ................................................ -->

        <div class="midbody" name="dragtarget">
            <ul class ="fri" id="sortable">

            </ul>
        </div>
        <div style="width:100px;height:100px"></div>

<!-- ................................................ -->

        <!-- <div class="door" id="door2" name="dragtarget">

        </div> -->

</div>
{% endblock %}
</body>
{% block script %}
<link rel="stylesheet"
href="http://code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
<script src="http://rubaxa.github.io/Sortable/Sortable.js"></script>
<script>
    
//   迴圈產生多個物件時function不要綁定ID!!他只會取一個
  $(function() {
    $( "#sortable" ).sortable({
      revert: true,
    });
    $( ".sta" ).draggable({
      connectToSortable: "#sortable",
      helper: "clone",
      revert: "invalid",
      drop: function(event, ui) {            
       $(this).changeClass('sortableone');}
    });
    $( "#sortable" ).sortable({
    drop: function() {
        var foodid = ui.draggable.attr('foodid');
        $.get('/fridge/sort' + foodid),function(data){
            alert(data)
            }
    }
    });
    $( "ul, li" ).disableSelection();
  });
  
  
  Sortable.create(sortable, {
    group: "items"
  });


  Sortable.create(devnull, {
  group: "items",

  onAdd: function (evt) {
    this.el.removeChild(evt.item);
  }
});



  function addSortableOutsideDrop(sortableInstance, callback)
		{
			var enableDragover = function(evt){ evt.preventDefault(); };
			document.documentElement.addEventListener("dragover", enableDragover);
			
			var setToInsideDrop = function(){ sortableInstance._isOutsideDrop = false; };
			// Set to inside drop if dropping inside the sortable element
			sortableInstance.el.addEventListener("drop", setToInsideDrop);
			// Set to inside drop if moving items across sortable lists
			Sortable.utils.on(sortableInstance.el, "add", setToInsideDrop);
			Sortable.utils.on(sortableInstance.el, "remove", setToInsideDrop);

			// On start, initialize to be outside drop
			Sortable.utils.on(sortableInstance.el, "start", function(evt){
				sortableInstance._isOutsideDrop = true;
			});
			// Check if is still outside drop, and if it is, do callback
			Sortable.utils.on(sortableInstance.el, "end", function(evt){
				if (sortableInstance._isOutsideDrop || typeof(sortableInstance._isOutsideDrop) == 'undefined')
					callback(evt);
			});
		}


  var draggableSortableOne = Sortable.create(sortable, {
			sort:true,
			group: "shared",
		});
    addSortableOutsideDrop(draggableSortableOne, function(evt){
		var el = evt.item;
		el.parentNode.removeChild(el);
		alert('Trashed: ' + el.textContent);
    });

        // $(function() {
        // //   $( ".sta" ).draggable({ snap: true,distance: 40  });
        // // //   $( ".sta" ).draggable({ snap: "div[name$='dragtarget']" });
        // $( ".sta" ).draggable({ snap: "div[name$='dragtarget']", snapMode: "inner",helper: "clone", opacity: "0.5",revert: "invalid", });
        // // //   $( "#draggable4" ).draggable({ grid: [ 20, 20 ] });
        // // //   $( "#draggable5" ).draggable({ grid: [ 80, 80 ] });
        // $(".door").droppable( { accept: ".sta", hoverClass: "dropHover", } ); 
        // });
</script>
<link rel="stylesheet"
href="http://code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
{% endblock %}

</html>

icethem/templates/base.html
<!DOCTYPE html>
<html lang="zh-tw">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy"
                crossorigin="anonymous">
    <script src="https://use.fontawesome.com/f57c5cc844.js"></script>
        
    <title>fridge</title>
</head>
{% block style %}{% endblock %}
<body>
{% include 'nav.html' %}

{% block 'main' %} {% endblock %}
{% if title != "stacks" %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!-- slim版本不支援ajax功能 -->
    <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
        {% endif %}
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4"
        crossorigin="anonymous"></script>
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment.min.js"></script> -->

{% block script %}{% endblock %}
</body>
</html>

icethem/templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-secondary mb-4">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <img src="{% static 'images/ice.jpg' %}" alt="">
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'fridge:index' %}">首頁
                </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'fridge:stacks' %}">存糧管理
                </a>
            </li>

        </ul>
        <!-- template引擎註解方法 -->
        {# if name == None #}
        <!-- template引擎註解方法 -->
        {% if request.COOKIES.name %}
        <span>{{ request.COOKIES.name }} 哩厚</span>
        {% else %}
        <span>請先</span>
        {% endif %}
        <ul class="navbar-nav float-right">

            <li class="nav-item">
                <!-- template引擎註解方法 -->
                {# if name == None #}
                <!-- template引擎註解方法 -->
                {% if request.COOKIES.name %}
                <a class="nav-link" href="{% url "user:logout" %}">登出</a>
                {% else %}
                <a class="nav-link" href="{% url "user:login" %}">登入</a>
                {% endif %}
            </li>
        </ul>

    </div>
</nav>

icethem/user/templates/user/index.html
{% extends 'base.html'%}
{% block content %}
<a href="{% url "user:create" %}" class="btn btn-primary mb-3"><i class="fa fa-plus-circle" aria-hidden="true"></i> 會員新增</a>
<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>姓名</th>
            <th>電子郵件</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
       {% for user in users%}
        <tr>
            <td>{{user.id}}</td>
            <td>{{user.username}}</td>
            <td>{{user.useremail}}</td>

            <td>
                <a href="{% url "user:update" user.id %}" class="btn btn-info mr-2">修改</a>
                <a href="{% url "user:delete" user.id %}" class="btn btn-danger">刪除</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

icethem/user/templates/user/update.html
{% extends 'base.html'%}
{% block content %}
<form method="POST">
    {% csrf_token %}   
    <div class="form-group row">
        <label for="username" class="col-sm-2 col-form-label">姓名</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" name="username" id="username" placeholder="User Name" value="{{user.username}}">
        </div>
    </div>
    <div class="form-group row">
        <label for="useremail" class="col-sm-2 col-form-label">電子郵件</label>
        <div class="col-sm-10">
            <input type="email" class="form-control" name="useremail" id="useremail" placeholder="User Email" value="{{user.useremail}}">
        </div>
    </div>
    <div class="form-group row">
        <label for="userbirth" class="col-sm-2 col-form-label">生日</label>
        <div class="col-sm-10">
            <input type="date" class="form-control" name="userbirth" id="userbirth" placeholder="Birthday" value="{{user.userbirth | date:'Y-m-d'}}">
        </div>
    </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-10 offset-md-2">
            <button type="submit" class="btn btn-primary"><i class="fa fa-bath" aria-hidden="true"></i> 修改</button>
        </div>
    </div>
</form>
{% endblock %}